from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

import tkinter as tk

from fwasset.core.types import FirmwareAsset


@runtime_checkable
class PanelHost(Protocol):
    """Protocol defining the interface that operation panels need from their host.

    FirmwareListPanel (and its base BaseFlashPanel) implement this protocol.
    Any class providing these methods can serve as a panel host, enabling
    operation panels to be tested in isolation.
    """

    usb_drive: tk.StringVar

    def _build_usb_selector_row(self, parent: Any) -> Any: ...
    def _refresh_usb(self) -> None: ...
    def _run_task(self, name: str, fn: Any, on_done: Any = None) -> None: ...
    def _selected_asset(self) -> FirmwareAsset | None: ...
    def _open_current_asset_dir(self) -> None: ...
    def _copy_asset_dir_path(self) -> None: ...
    def _copy_primary_file_path(self) -> None: ...
    def _launch_tool_and_open_asset_dir(self) -> None: ...
    def get_global_usb_drive(self) -> str: ...